apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: ionir-nvme-tcp
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8,nvme-tcp
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/nvme-tcp.conf
