apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: ionir-intel-iommu
spec:
  config:
    ignition:
      version: 3.1.0
  kernelArguments:
    - intel_iommu=on