apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: ionir-vfio-mmu
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8,options%20vfio%20enable_unsafe_noiommu_mode=1
          mode: 420
          overwrite: true
          path: /etc/modprobe.d/vfio-noiommu.conf
        - contents:
            source: data:text/plain;charset=utf-8,vfio_iommu_type1
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/vfio-mmu-type1.conf
