apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: ionir-uio-pci-generic
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8,uio_pci_generic
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/uio_pci_generic.conf
